---
title: "Experiment Design -- Case Study 01"
output: html_notebook
---

## Introduction

In this notebook, you are asked to perform the statistical analysis of a simulated experiment. This experiment is the same as the "Shield" experiment described in Week 5. The data for this experiment can be found in the file "labdata.csv"

## The Experiment

A ballistics laboratory is in the process of being certified for the evaluation of shielding technology. As part
of this process, the laboratory must provide evidence that a certain callibration procedure produces results
that are consistent with a reference equipment from the Department of Defence.

The procedure in question consists of shooting a standardized steel cube against a 320mm-thick alluminum
target and measuring the resulting hole area. From previous measurements under similar conditions, the
standard deviations of the observations of this laboratory and of the Department of Defence can be roughly
estimated as:

- $\hat{\sigma}_{Lab}: 5mm^2$
- $\hat{\sigma}_{DD}: 10mm^2$

The certification authority demands that the mean hole area generated by this procedure in the lab be the
same as the one from the reference equipment, and tolerates deviations no greater than 4 mm2. Since this
certification is quite important for the laboratory, the engineer in charge of the process decides that he wants
a significance level $\alpha$ = 0.01 and a power of (1 − $\beta$) = 0.9 for the smallest effect size of practical significance.

Assume that the engineer has free access to both the reference and the local test equipments (so that in
theory he could obtain as many observations as needed), but that each observation is relatively expensive (so
that in practice he wants to use the smallest sample size possible).

## Activities

Your Task is to answer the following Question:

"Is the mean hole size generated by the laboratory in conformity with the one generated by the reference equipment?"

1. Describe the experimental design required to answer the technical question of interest. Detail the
hypotheses being tested and the relevant design for testing those hypotheses.
2. Calculate the required sample size for the experiment. For the sake of simplicity you can consider equal
sample sizes for both.
3. Obtain the experimental data from the "labdata.csv" file
4. Perform the statistical analysis using the observations contained in the data file. This includes:
    1. Perform the actual test of statistical significance;
    1. Estimate the effect size (including the confidence interval);
    1. Check the assumptions of your test;
    1. Describe your conclusions and recommendations.
    
Remember to use graphs to better show the necessary quantities.
